global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["server:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Если добавишь smartctl_exporter отдельным сервисом в compose:
  # - job_name: "smartctl"
  #   static_configs:
  #     - targets: ["smartctl-exporter:9633"]
